server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: hospital-management

  datasource:
    # 1. localhost -> ${DB_HOST:localhost} (Mặc định là localhost nếu chạy ngoài, lấy từ biến DB_HOST nếu chạy Docker)
    # 2. 5454 -> ${DB_PORT:5454} (Đồng bộ port với container Database)
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5454}/hospital_db?options=-c%20timezone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456789}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # Khi lên Docker nên dùng 'update' để tránh mất dữ liệu mỗi lần restart container
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    ptit.hospitalmanagementsystem: DEBUG # Sửa lại package cho đúng project của bạn

jwt:
  signerKey: ${JWT_SIGNER_KEY:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef}
  valid-duration: 3600
  refreshable-duration: 86400